### ISSUE TITLE
[META] Cleaning up 

### ISSUE THREAD

**Issue by ghost** [lsglab/frontend-sapper#101]
#100 introduced a few shortcomings, and the lack of commits within the past months has created some additional problems. This is a meta issue to clean up the codebase a little and have it adhere to our standards. Discussion will proceed on Signal.

- [x] The `src/routes/index.svelte` file doesn't adhere to [Atomic Design](https://atomicdesign.bradfrost.com/table-of-contents/) and contains numerous nested components. (Fixed in #102 and #112)
- [ ] The `tailwind.config.js` file introduces custom colors that don't match the default color palette. Either we generate a completely own color palette based on the current custom colors, or we switch from these additional colors to the default color palette. I believe mixing both hurts the uniformity. (EDIT: [This extension](https://marketplace.visualstudio.com/items?itemName=bourhaouta.tailwindshades) might help with color scheme generation, overriding the default classes)
- [ ] Packages in `package.json` haven't been updated in a while (my fault) and contain security vulnerabilities. I recommend bumping each package individually and seeing if compilation is still successful afterwards. There are a few incompatibilities between related packages and their versions, which is why some have been left intentionally outdated.
- [x] TailwindCSS v2 has been out for quite some time now and I haven't migrated yet. We're loosing out on some cool new features, however after upgrading we might also have to consider a better compiled style caching mechanism.
- [ ] There are some instances of `px` unit usage in the projects css files. Pixel density depends on the monitors resolution and size (f.e. retina screens, high-res monitors, ultrawides...), which means that the usage of this unit is highly unreliable (please correct me if I'm wrong). We should replace all occurrences with a viewport-dependent unit such as `vw`, `vh`, `%`, flexbox etc. -> The ultimate goal is to make everything relative
- [x] Using `px` and other fixed values brings another shortcoming, which is media queries. They introduce inconsistency among different screen sizes and break fluid design, which is something that at least I myself think is a lot nicer than having breakpoints and manually testing different website sizes for issues. Ideally, the whole website (including paddings, margins etc) should be fluid and without breakpoints.

**Comment by Lacrimus** [comment]
> 
>     * [ ]  The `src/routes/index.svelte` file doesn't adhere to [Atomic Design](https://atomicdesign.bradfrost.com/table-of-contents/) and contains numerous nested components.
As beneficial the structure of atomic design might be, I discourage transferring to a new scheme while content is being created (which is where I think our focus should lie on).
> 
>     * [ ]  Sapper will never reach version 1.0 and its successor SvelteKit is currently under development. When are we planning to migrate?
Unfortunately, I don't see this as an option at all. Migration will prove difficult as our entire knowledge and architecture is based on Sapper. Switching to something that "is still being worked on in a private repo" (see https://svelte.dev/blog/whats-new-in-svelte-january-2021) will delay actual progress even further and make the project more unstable. Sapper itself is still very modern, feature rich and fulfils our demands, so there is no need to change the running system.

> #100 introduced a few shortcomings, and the lack of commits within the past months has created some additional problems.
Especially _because_ we are in time with few commits and changes in the code, we need to put all of our time into content creation instead of total restructuring.

Concerning your other bullet points, I'll take a look at the px and @media matter.
But overall, it is nice to see some activity here again.

**Comment by Flosi23** [comment]
As Lacrimus, I too dont think that replacing sapper or migrating to a different farmework is an option. We agreed on the tools we use and changing them will only slow down or terminate progress.

As for the colors, i would prefer a custom color palette over the default one because it gives us more flexibility. I will open up a separate issue for applying the design used in index.svelte to all other subpages, including the colors. 

I will also open a separate issue for making index.svelte AtomicDesign conform.

**Comment by Flosi23** [comment]
I looked into the media query used in section.svelte and i am sure that this can be done using the breakpoints provided by tailwind. I'll open up a seperate issue to deal with this fix.
